//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.DTO1
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAN_VIEN
    {  
        public string MaNhanVien { get; set; }
        public string HoTen { get; set; }
        public string DanToc { get; set; }
        public string GioiTinh { get; set; }
        public string CMND { get; set; }
        public string SoDienThoai { get; set; }
        public string QueQuan { get; set; }
        public DateTime NgaySinh { get; set; }
        public bool TrangThai { get; set; }
        public bool isAdmin { get; set; }
    }
}
