//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.DTO1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public int GiaBan { get; set; }
        public int SoLuong { get; set; }
        public string MaNXB { get; set; }
        public string MaLoaiSach { get; set; }
    }
}
